### ISSUE TITLE
Curl "Put" command doesn't work

### ISSUE THREAD

**Issue by StefanBabinec** [cuusoo/electricity-load-forecasting-2017#1]
Hello.

We are registered contest participants (Tangent Works).

We are trying your "PUT" Curl command:

curl -H "Authorization: Bearer our_token" -H "Accept: application/json" -H "Content-type: application/json" -X PUT -d '{"result":"2370"}' "https://forecasting.cuusoo.com/results/1503586800"

And we get: 500 Internal Server Error.

There is no problem with "GET" commands.

Any advice ?

Best Regards.

Stefan Babinec
Tangent Works Team.

**Comment by kazupon** [comment]
Thank you for your reporting!

Hmm, 🤔 it's strange.
In my the below emviroments,  it's works.

- OS: Mac OS X El Capitan (10.11.5)
- curl version: 7.43.0

By the way, Could you provide the your enviments please?

Would you check the python example with provided by us?

We would like to know you if it works or not. 🙏

**Comment by kazupon** [comment]
As additional information, the API server detected the parameter of the request as invalid JSON format.

**Comment by StefanBabinec** [comment]
Hello.

My environment:

- OS: Windows 8.1 Pro
- curl version: 7.55.1

I tried to send PUT commands to different REST services (just in the case that something is not correctly installed) and everything works as expected.

Anyway. I tried the same on Ubuntu with curl version 7.35.0 and it works correctly. 
So from my side it is OK.

Best Regards.
Stefan.

**Comment by kazupon** [comment]
Thank for your quick response.
Good luck! 👍
